spring:
  datasource:
    url: jdbc:mysql://haengyeo_mysql:3306/restock_db
    username: user
    password: b12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # Redis Configuration (updated)
  data:
    redis:
      host: ${SPRING_REDIS_HOST:haengyeo_redis}
      port: ${SPRING_REDIS_PORT:6379}

server:
  port: 8090

logging:
  level:
    com.sparta.hanghae_restock: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
