spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restock_db  # 데이터베이스 URL
    username: your_username  # 실제 환경에서 사용하는 사용자명
    password: your_password  # 실제 환경에서 사용하는 비밀번호
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL Dialect
        format_sql: true  # SQL 로그 출력
    hibernate:
      ddl-auto: update  # 개발 환경에서 자동으로 스키마 업데이트
    open-in-view: false
  sql:
    init:
      mode: always  # 애플리케이션 시작 시 SQL 초기화

server:
  port: 9000

logging:
  level:
    com.sparta.sparta_reviewapi: INFO  # 애플리케이션 로깅 레벨
    org.hibernate.SQL: DEBUG  # Hibernate SQL 로그
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Hibernate 파라미터 바인딩 로그
