spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restock_db
    username: root
    password: b12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9000

logging:
  level:
    com.sparta.sparta_reviewapi: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


#     url: jdbc:mysql://haengyeo_mysql:3306/restock_db // ???? url??
#     port: 8090 // ???? port
#    username: root
#    password: b12345678